env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
rules:
  no-inner-declarations: 1
  '@typescript-eslint/no-explicit-any': 1
  '@typescript-eslint/camelcase': 1
  '@typescript-eslint/explicit-function-return-type': 1
  '@typescript-eslint/no-use-before-define': 1

parserOptions:
  ecmaVersion: 2018
  sourceType: module